# Generated by Django 3.2 on 2021-05-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '__first__'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel', verbose_name='チャンネル'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
