# Generated by Django 3.2 on 2021-05-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210513_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
    ]
